### ========== environment ==========
### get all environments
GET http://{{baseURL}}/api/v1/metadata/env
Content-Type: application/json

### get environment by id
GET http://{{baseURL}}/api/v1/metadata/env/1
Content-Type: application/json

### add new environment
POST http://{{baseURL}}/api/v1/metadata/env
Content-Type: application/json

{"env_name": "new_environment"}

### update environment by id
POST http://{{baseURL}}/api/v1/metadata/env/1
Content-Type: application/json

{"env_name": "test123", "del_flag": 1}

### ========== middleware ==========
### get all middleware cluster
GET http://{{baseURL}}/api/v1/metadata/middleware-cluster
Accept: application/json

### get middleware cluster by id
GET http://{{baseURL}}/api/v1/metadata/middleware-cluster/2
Accept: application/json

### add new middleware cluster
POST http://{{baseURL}}/api/v1/metadata/middleware-cluster
Content-Type: application/json

{"cluster_name": "test", "env_id": 1}

### update middleware-cluster by id
POST http://{{baseURL}}/api/v1/metadata/middleware-cluster/2
Content-Type: application/json

{"cluster_name": "new_middleware_cluster", "del_flag": 1}

### get all middleware server
GET http://{{baseURL}}/api/v1/metadata/middleware-server
Accept: application/json

### get middleware server by id
GET http://{{baseURL}}/api/v1/metadata/middleware-server/1
Accept: application/json

### add new middleware server
POST http://{{baseURL}}/api/v1/metadata/middleware-server
Content-Type: application/json

{"cluster_id_middleware": 1, "server_name": "middleware_server", "middleware_role": 1, "host_ip": "123.123.123.1", "port_num": 12}

### update middleware-cluster by id
POST http://{{baseURL}}/api/v1/metadata/middleware-server/1
Content-Type: application/json

{"server_name": "ccc", "del_flag": 1}


### =============== mysql-cluster ===================

### get all mysql clusters
GET http://{{baseURL}}/api/v1/metadata/mysql-cluster
Accept: application/json

### get mysql cluster by id
GET http://{{baseURL}}/api/v1/metadata/mysql-cluster/1
Accept: application/json

### add new mysql cluster
POST http://{{baseURL}}/api/v1/metadata/mysql-cluster
Content-Type: application/json

{"cluster_name": "api_test"}

### update mysql cluster by id
POST http://{{baseURL}}/api/v1/metadata/mysql-cluster/154
Content-Type: application/json

{"cluster_name": "api_test", "del_flag": 1}



### =============== mysql-server ===================

### get all mysql servers
GET http://{{baseURL}}/api/v1/metadata/mysql-server
Accept: application/json

### get mysql server by id
GET http://{{baseURL}}/api/v1/metadata/mysql-server/1
Accept: application/json

### add new mysql server
POST http://{{baseURL}}/api/v1/metadata/mysql-server
Content-Type: application/json

{"host_ip": "192.168.1.1", "port_num": 3306}

### update mysql server by id
POST http://{{baseURL}}/api/v1/metadata/mysql-server/93
Content-Type: application/json

{"host_ip": "192.168.1.1", "port_num": 3306, "del_flag": 1}





### get all databases
GET http://{{baseURL}}/api/v1/metadata/db
Accept: application/json

### get database by id
GET http://{{baseURL}}/api/v1/metadata/db/1
Accept: application/json

### add new database
POST http://{{baseURL}}/api/v1/metadata/db
Content-Type: application/json

{"db_name": "db2","owner_id": "1", "env_id": "5"}

### get database by id
POST http://{{baseURL}}/api/v1/metadata/db/4
Content-Type: application/json

{"db_name": "db3", "del_flag": 1}

### get all monitor systems
GET http://{{baseURL}}/api/v1/metadata/monitor-system
Accept: application/json

### get monitor system by id
GET http://{{baseURL}}/api/v1/metadata/monitor-system/1
Accept: application/json

### add new monitor system
POST http://{{baseURL}}/api/v1/metadata/monitor-system
Content-Type: application/json

{"system_name": "ms7", "system_type":"1","host_ip": "127.0.0.1", "port_num": "3314","port_num_slow": "3315", "base_url": "http://127.0.0.1/prometheus/api/v1/"}

### get monitor system by id
POST http://{{baseURL}}/api/v1/metadata/monitor-system/5
Content-Type: application/json

{"system_name": "ms9", "del_flag": 1}
