### get all environments
GET http://127.0.0.1:6090/api/v1/metadata/env
Accept: application/json

### get environment by id
GET http://127.0.0.1:6090/api/v1/metadata/env/1
Accept: application/json

### add new environment
POST http://127.0.0.1:6090/api/v1/metadata/env
Content-Type: application/json

{"env_name": "test123123123"}

### get environment by id
POST http://127.0.0.1:6090/api/v1/metadata/env/1
Content-Type: application/json

{"env_name": "test", "del_flag":0}




