### get all monitor systems
GET http://{{baseURL}}/api/v1/metadata/monitor-system
Accept: application/json

### get all monitor systems by env_id
GET http://{{baseURL}}/api/v1/metadata/monitor-system/env/1
Accept: application/json

### get monitor system by id
GET http://{{baseURL}}/api/v1/metadata/monitor-system/get/1
Accept: application/json

### get all monitor systems by host-info
GET http://{{baseURL}}/api/v1/metadata/monitor-system/host-info?hostIp=127.0.0.1&portNum=3307
Accept: application/json

### add new monitor system
POST http://{{baseURL}}/api/v1/metadata/monitor-system
Content-Type: application/json

{"system_name": "ms4", "system_type":1, "host_ip": "127.0.0.1", "port_num": 3306, "port_num_slow": 3308, "base_url": "http://127.0.0.1/prometheus/api/v1/", "env_id": 1}

### update monitor system by id
POST http://{{baseURL}}/api/v1/metadata/monitor-system/update/1
Content-Type: application/json

{"system_name": "ms8", "port_num": 3300, "del_flag": 1}

### delete monitor system by id
POST http://{{baseURL}}/api/v1/metadata/monitor-system/delete/2
Content-Type: application/json
