### GetEnv
GET http://{{baseURL}}/api/v1/metadata/env
Accept: application/json

### GetEnvByID
GET http://{{baseURL}}/api/v1/metadata/env/get/2
Accept: application/json

### GetEnvByName
GET http://{{baseURL}}/api/v1/metadata/env/env-name/hi
Accept: application/json

### AddEnv
POST http://{{baseURL}}/api/v1/metadata/env
Content-Type: application/json

{"env_name": "6616", "del_flag": 1}

### UpdateEnvByID
POST http://{{baseURL}}/api/v1/metadata/env/update/2
Content-Type: application/json

{"env_name": "rel","del_flag": 0}

### DeleteEnvByID
POST http://{{baseURL}}/api/v1/metadata/env/delete/9
Content-Type: application/json
