### get all appsystems
GET http://{{baseURL}}/api/v1/metadata/app-system
Accept: application/json

### get appsystem by id
GET http://{{baseURL}}/api/v1/metadata/app-system/66
Accept: application/json

### add new appsystem
POST http://{{baseURL}}/api/v1/metadata/app-system
Content-Type: application/json

{"system_name": "tes123t123123123","level":1,"owner_id":1,"owner_group":"k"}

### get appsystem by id
POST http://{{baseURL}}/api/v1/metadata/app-system/66
Content-Type: application/json

{"system_name": "1", "del_flag":0}