### get all middleware cluster
GET http://{{baseURL}}/api/v1/metadata/middleware-cluster
Accept: application/json

### get middleware cluster by id
GET http://{{baseURL}}/api/v1/metadata/middleware-cluster/3
Accept: application/json

### add new middleware cluster
POST http://{{baseURL}}/api/v1/metadata/middleware-cluster
Content-Type: application/json

{"cluster_name": "connection_test", "env_id": 1}

### update middleware-cluster by id
POST http://{{baseURL}}/api/v1/metadata/middleware-cluster/14
Content-Type: application/json

{"cluster_name": "ccc", "del_flag": 1}

###

