### GetEnv
GET http://127.0.0.1:6090/api/v1/metadata/env
Content-Type: application/json

### GetEnvByID
GET http://127.0.0.1:6090/api/v1/metadata/env/get/2
Content-Type: application/json

### GetEnvByName
GET http://127.0.0.1:6090/api/v1/metadata/env/env-name/hi
Content-Type: application/json

### AddEnv
POST http://127.0.0.1:6090/api/v1/metadata/env
Content-Type: application/json

{"env_name": "6616", "del_flag": 1}

### UpdateEnvByID
POST http://127.0.0.1:6090/api/v1/metadata/env/update/3
Content-Type: application/json

{"env_name": "rel3","del_flag": 1}

### DeleteEnvByID
POST http://127.0.0.1:6090/api/v1/metadata/env/delete/9
Content-Type: application/json
