@baseURL = 127.0.0.1:6090

### GetUser
GET http://{{baseURL}}/api/v1/metadata/user
Content-Type: application/json

### GetUserByName
GET http://{{baseURL}}/api/v1/metadata/user/user-name/user_name
Content-Type: application/json

### GetUserByID
GET http://{{baseURL}}/api/v1/metadata/user/get/5
Content-Type: application/json

### GetUserByEmployeeID
GET http://{{baseURL}}/api/v1/metadata/user/employee-id/employee_id
Content-Type: application/json

### GetUserByAccountName
GET http://{{baseURL}}/api/v1/metadata/user/account-name/account_name
Content-Type: application/json

### GetUserByEmail
GET http://{{baseURL}}/api/v1/metadata/user/email/email
Content-Type: application/json

### GetUserByTelephone
GET http://{{baseURL}}/api/v1/metadata/user/telephone/telephone
Content-Type: application/json

### GetUserByMobile
GET http://{{baseURL}}/api/v1/metadata/user/mobile/mobile
Content-Type: application/json

### AddUser 
POST http://{{baseURL}}/api/v1/metadata/user
Content-Type: application/json

 {"department_name": "department_name","employee_id": "employee_id", "telephone": "telephone","role": 2,"del_flag": 0,"user_name": "user_name21","account_name": "account_na1me2","email": "emai12l","mobile": "mobile" }

### UpdateUserByID
POST http://{{baseURL}}/api/v1/metadata/user/update/5
Content-Type: application/json

  {"department_name": "department_name","employee_id": "employee_id12", "telephone": "telephone","role": 2,"del_flag": 1,"user_name": "user_name21","account_name": "account_name21","email": "emai12l","mobile": "mobile" }

### DeleteUserByID
POST http://{{baseURL}}/api/v1/metadata/user/delete/1
Content-Type: application/json




















        	
        