@baseURL = 127.0.0.1:6090

### GetEnv
GET http://{{baseURL}}/api/v1/metadata/env
Content-Type: application/json

### GetEnvByID
GET http://{{baseURL}}/api/v1/metadata/env/get/2
Content-Type: application/json

### GetEnvByName
GET http://{{baseURL}}/api/v1/metadata/env/env-name/hi
Content-Type: application/json

### AddEnv
POST http://{{baseURL}}/api/v1/metadata/env
Content-Type: application/json

{"env_name": "61616", "del_flag": 1}

### UpdateEnvByID
POST http://{{baseURL}}/api/v1/metadata/env/update/35
Content-Type: application/json

{"env_name": "re1l3","del_flag": 1}

### DeleteEnvByID
POST http://{{baseURL}}/api/v1/metadata/env/delete/9
Content-Type: application/json
